### ISSUE TITLE
Allow user to reorder lines (isolates) in the heatmap by drag and drop or to sort them by name

### ISSUE THREAD

**Issue by mahafarhat** [IQSS/gentb-site#40]
for example in Italian dataset it would be very useful if the user can reorder the lines by Italian1, Italian2, Italian3 etc to Italian10 by draging lines to the right place.

Or alternatively ordering the lines by hierarchical clustering of the colors/probabilites would be even better.

**Comment by doctormo** [comment]
Should this be assigned to me?

**Comment by mahafarhat** [comment]
I was going to try some clustering from within the TBpredict.R code, but if there is a simple way by which the user can reorder lines interactively from the heatmap that would be even better

**Comment by mahafarhat** [comment]
pushed some changes to the TBpredict script that should do this now. But I inadvertently pushed to live!! how do I update the master?

**Comment by mahafarhat** [comment]
after testing found a bug that I've now fixed, can you please redeploy, or possibly can you teach me how to do this so I don't have to bother you every time? perhaps at our next meeting but redeploy for now so I finish the testing

**Comment by doctormo** [comment]
I've deployed your changes to live.

**Comment by mahafarhat** [comment]
I'm still getting a 503 service temporarily unavailable more than half an hour after

**Comment by doctormo** [comment]
This should be reported as a separate issue (always), I've restarted the server, but we could do with tracking the fix to the deployment script that caused the issue.

**Comment by mahafarhat** [comment]
ok this should be fixed I will close it
