### ISSUE TITLE
New User login not working

### ISSUE THREAD

**Issue by mahafarhat** [IQSS/gentb-site#53]
Message from a prospective new user 

"I’m trying to logging in after registering myself, but it does not recognize my password. I tried the recovery password function but it does not work and it displays the following:"

 Error is: "Page no found. 404 Error"

**Comment by mahafarhat** [comment]
doctormo: I've pushed an update which should fix the password reset, I've set the
settings to try and get emails out so people can start using it right
away.

Please test too. I had to reorganise the urls to make it work right.

**Comment by mahafarhat** [comment]
the login for a new user still doesnot work, after hitting submit nothing happens

**Comment by doctormo** [comment]
OK I've pushed a further update. I've removed a lot of the customised registration form, it was saving the passwords into the database as clear-text (a very serious security problem). Customising user forms needs to always use django forms as base classes because they do the security thing right.

This clear text password was why users couldn't log in once registered. The password was not hashed correctly.

All users who registered recently will need to reset their passwords using the password reset form or have an administrator reset it for them.

**Comment by mahafarhat** [comment]
OK tried to reset the password, the website states an email was sent. But now 10min later no email has been received.

**Comment by mahafarhat** [comment]
ok just tested it again, new account set up is working, but password reset email is still not being sent

**Comment by doctormo** [comment]
Emails were tested on live as working, but routing through gmail is causing us a lot of problems. Does orchestra not have an smtp service we can use to send emails instead?

**Comment by mahafarhat** [comment]
I'm pretty sure they do, please open a ticket with them if needed at rchelp@hms.harvard.edu

**Comment by doctormo** [comment]
I've fixed all the existing users who set up their accounts. They should be able to log in now without the reset password function.

**Comment by doctormo** [comment]
Confirmed on live, each user's password worked with their username.
