### ISSUE TITLE
manual predict broken

### ISSUE THREAD

**Issue by mahafarhat** [IQSS/gentb-site#97]
got the following error after selecting one mutation for prediciton:

Attaching package: ‘jsonlite’ The following object(s) are masked from ‘package:utils’: View Error in eval(expr, envir, enclos) : object 'INS_CF_4247350_i836TTCCAGAATATTGG_279_embB' not found Execution halted

**Comment by doctormo** [comment]
This error is because there are mutations which were removed from the database with the wg dataset, these were marked as predictors and thus entered the matrix.csv file that way. Not being in the database means they're not available to the randomForest process and it doesn't like missing columns.

**Comment by mahafarhat** [comment]
This seems nearly impossible as the predictor list was generated only from the targeted data set.

**Comment by doctormo** [comment]
It explains why the mutation that causes an error isn't in our database. When I add it to the matrix.csv the error changes to a new and different SNP name.

**Comment by doctormo** [comment]
This should be fixed and live now.

**Comment by mahafarhat** [comment]
still not fixed, I tried three different pncA mutations and I get the following error:
 	
Genetic information: Mutations are not available in prediction: SNP_CN_2289103_T139C_T47A_pncA, SNP_CN_2289030_T212G_H71P_pncA ...

**Comment by mahafarhat** [comment]
and just tried mutations in a handful of other genes still with the same issue

**Comment by doctormo** [comment]
There seemed to be an issue with csv vs. line break format. That's fixed now. Can you try again?
